# Generated by Django 5.2.3 on 2026-01-07 15:23

import SKT_account.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', SKT_account.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('IDEntreprise', models.AutoField(primary_key=True, serialize=False)),
                ('Entreprise_Name', models.CharField(max_length=255)),
                ('Entreprise_Licence_Date_Start', models.DateField(auto_now_add=True)),
                ('Entreprise_Licence_Date_End', models.DateField(blank=True, null=True)),
                ('Entreprise_Licence_Statut', models.CharField(choices=[('ACT', 'Active'), ('DIS', 'Disable'), ('ARC', 'Archive')], default='ACT', max_length=3)),
                ('Entreprise_Num_Customer_Allow', models.IntegerField(default=0, error_messages={'blank': 'Le nombre de clients autorisés est requis.', 'invalid': 'Veuillez saisir un entier valide.'}, help_text='Entier compris entre 0 et 99\u202f999.', validators=[django.core.validators.MinValueValidator(0, message='Le nombre de clients autorisés peut pas être négative (min = 0).'), django.core.validators.MaxValueValidator(999, message='Le nombre de clients autorisés ne peut pas dépasser \u202f999.')])),
                ('Entreprise_Num_Customer_Create', models.IntegerField(default=0, error_messages={'blank': 'Ce champ est requis.', 'invalid': 'Veuillez saisir un entier valide.'}, help_text='Entier ≥ 0 et ≤ au nombre de clients autorisées ', validators=[django.core.validators.MinValueValidator(0, message='La valeur ne peut pas être négative.')])),
                ('Entreprise_Num_User_Allow', models.IntegerField(default=0, error_messages={'blank': "Le nombre d'utilisateurs autorisés est requis.", 'invalid': 'Veuillez saisir un entier valide.'}, help_text='Entier compris entre 0 et 99\u202f999.', validators=[django.core.validators.MinValueValidator(0, message="Le nombre d'utilisateurs ne peut pas être négative (min = 0)."), django.core.validators.MaxValueValidator(99999, message="Le nombre d'utilisateurs ne peut pas dépasser 99\u202f999.")])),
                ('Entreprise_Num_User_Create', models.IntegerField(default=0, error_messages={'blank': 'Ce champ est requis.', 'invalid': 'Veuillez saisir un entier valide.'}, help_text="Entier ≥ 0 et ≤ au nombre d'utilisateurs autorisés ", validators=[django.core.validators.MinValueValidator(0, message='La valeur ne peut pas être négative.')])),
                ('Entreprise_Num_Supervisor_Allow', models.IntegerField(default=0, error_messages={'blank': 'Le nombre de superviseurs autorisés est requis.', 'invalid': 'Veuillez saisir un entier valide.'}, help_text='Entier compris entre 0 et 9\u202f999.', validators=[django.core.validators.MinValueValidator(0, message='Le nombre de superviseur ne peut pas être négative (min = 0).'), django.core.validators.MaxValueValidator(9999, message='Le nombre de superviseur ne peut pas dépasser 9\u202f999.')])),
                ('Entreprise_Num_Supervisor_Create', models.IntegerField(default=0, error_messages={'blank': 'Ce champ est requis.', 'invalid': 'Veuillez saisir un entier valide.'}, help_text='Entier ≥ 0 et ≤ au nombre de superviseurs autorisés ', validators=[django.core.validators.MinValueValidator(0, message='La valeur ne peut pas être négative.')])),
                ('Entreprise_Num_Group_Allow', models.IntegerField(default=0, error_messages={'blank': 'Le nombre de groupe autorisés est requis.', 'invalid': 'Veuillez saisir un entier valide.'}, help_text='Entier compris entre 0 et 9\u202f999.', validators=[django.core.validators.MinValueValidator(0, message='Le nombre de groupe ne peut pas être négative (min = 0).'), django.core.validators.MaxValueValidator(9999, message='Le nombre de groupe ne peut pas dépasser 9\u202f999.')])),
                ('Entreprise_Num_Group_Create', models.IntegerField(default=0, error_messages={'blank': 'Ce champ est requis.', 'invalid': 'Veuillez saisir un entier valide.'}, help_text='Entier ≥ 0 et ≤ au nombre de groupes autorisés ', validators=[django.core.validators.MinValueValidator(0, message='La valeur ne peut pas être négative.')])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('Entreprise_Num_Customer_Allow__gte', 0), ('Entreprise_Num_Customer_Allow__lte', 999)), name='chk_allow_between_0_and_999'), models.CheckConstraint(condition=models.Q(('Entreprise_Num_Customer_Create__gte', 0), ('Entreprise_Num_Customer_Create__lte', models.F('Entreprise_Num_Customer_Allow'))), name='chk_customer_create_lte_allow'), models.CheckConstraint(condition=models.Q(('Entreprise_Num_User_Create__gte', 0), ('Entreprise_Num_User_Create__lte', models.F('Entreprise_Num_User_Allow'))), name='chk_user_create_lte_allow'), models.CheckConstraint(condition=models.Q(('Entreprise_Num_Supervisor_Create__gte', 0), ('Entreprise_Num_Supervisor_Create__lte', models.F('Entreprise_Num_Supervisor_Allow'))), name='chk_supervisor_create_lte_allow'), models.CheckConstraint(condition=models.Q(('Entreprise_Num_Group_Create__gte', 0), ('Entreprise_Num_Group_Create__lte', models.F('Entreprise_Num_Group_Allow'))), name='chk_group_create_lte_allow')],
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Compte_Image', models.ImageField(default='SKM_Pictures/Profile/default.png', upload_to='SKM_Pictures/Profile')),
                ('Compte_IDEntreprise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SKT_account.entreprise')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('SKT_account.user',),
            managers=[
                ('objects', SKT_account.models.UserManager()),
            ],
        ),
    ]
